### ISSUE TITLE
GLReadback error when stopping recording

### ISSUE THREAD

**Issue by olokobayusuf** [natsuite/NatCorder-Performance-Extensions#13]
```
E/AndroidRuntime: FATAL EXCEPTION: NatRender GLReadback
    Process: com.budleid, PID: 29631
    java.lang.IllegalStateException: Image is already closed
        at android.media.Image.throwISEIfImageIsInvalid(Image.java:72)
        at android.media.ImageReader$SurfaceImage.getWidth(ImageReader.java:829)
        at api.natsuite.natrender.GLReadback$1.onImageAvailable(GLReadback.java:114)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:798)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by olokobayusuf** [comment]
This should be fixed in [NCPX 0.0.3](https://www.npmjs.com/package/api.natsuite.ncpx)
